/**
 * Centralized frontend runtime configuration.
 * All runtime-variable values come from VITE_* env vars with safe fallbacks
 * for backward compatibility with the hosted (Lovable) environment.
 */

/**
 * Regional reverse proxy host. ALL Supabase traffic from the browser must go
 * through this host because the direct *.supabase.co domain is blocked by
 * Roskomnadzor in Russia. Without this, RU users cannot log in or load data
 * unless they have a VPN.
 */
const PROXY_URL = "https://api.wbgen.ru";

/**
 * Resolve the Supabase URL used by the browser client.
 *
 * Even if VITE_SUPABASE_URL accidentally points to *.supabase.co (e.g. the
 * .env file gets regenerated by tooling), we hard-rewrite it to the regional
 * proxy. This guarantees Russian users keep working without a VPN.
 */
function resolveSupabaseUrl(): string {
  const raw = (import.meta.env.VITE_SUPABASE_URL || PROXY_URL).trim();
  try {
    const host = new URL(raw).hostname.toLowerCase();
    if (host.endsWith(".supabase.co") || host.endsWith(".supabase.in")) {
      return PROXY_URL;
    }
    return raw;
  } catch {
    return PROXY_URL;
  }
}

export const supabaseUrl: string = resolveSupabaseUrl();

export const supabasePublishableKey: string =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndWl5YWJwbmdqa2F2eW9zYnphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjcwMDEsImV4cCI6MjA3MTcwMzAwMX0.RrDztNYkAy0-PMb4j4A9XG28hROv9PsMw9EyG8dFcco";

export const supabaseProjectId: string =
  import.meta.env.VITE_SUPABASE_PROJECT_ID || "xguiyabpngjkavyosbza";

export const publicSiteUrl: string =
  import.meta.env.VITE_PUBLIC_SITE_URL || "https://wbgen.ru";

export const supportTelegramUrl: string =
  import.meta.env.VITE_SUPPORT_TELEGRAM_URL || "https://t.me/wbgen_support";

export const telegramGroupUrl: string =
  import.meta.env.VITE_TELEGRAM_GROUP_URL || "https://t.me/wbgen_official";
