// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseUrl, supabasePublishableKey, supabaseProjectId } from '@/config/runtime';

// Safe storage wrapper for Telegram WebView compatibility
// localStorage may be unavailable or cleared in some WebView environments
const safeStorage = (() => {
  try {
    localStorage.setItem('__storage_test__', '1');
    localStorage.removeItem('__storage_test__');
    return localStorage;
  } catch {
    // Fallback to in-memory storage for Telegram WebView and restricted environments
    const store: Record<string, string> = {};
    return {
      getItem: (key: string) => store[key] ?? null,
      setItem: (key: string, value: string) => { store[key] = value; },
      removeItem: (key: string) => { delete store[key]; },
    };
  }
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: safeStorage,
    storageKey: `sb-${supabaseProjectId}-auth-token`,
    persistSession: true,
    autoRefreshToken: true,
  }
});
